# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789ca27c73a78db91361c38762da8901f7832c40c096c1bfb49555cac6827cccc373caaeeb2fbe00e52b4915feffcd45cd34044b1a6a2deb66e59844066f1594

test:
  secret_key_base: b9163b730138d0d7848c4e193088422772acd2d8208e34fb20840a39769d19c2a4f8c0c72552955819d9e3c81041ae08f0f746065499565d12bc3f49e7d5eff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
